name: CI (PR checks)

on:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      # あれば実行（無ければコメントアウトでOK）
      - name: Lint
        run: npm run lint --if-present
      - name: Typecheck
        run: npm run typecheck --if-present
      - name: Unit tests
        run: npm test --if-present

      # Pages想定で本番ビルドが通るか確認（baseの不備を早期検知）
      - name: Build (Astro)
        env:
          DEPLOY_TARGET: pages   # astro.config.mjs で base/site の分岐に使用
        run: npm run build
